name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nastaviť Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Vygenerovať poznámky
        run: |
          go run main.go poznamky

      - name: Nastaviť GH Pages
        uses: actions/configure-pages@v4
      - name: Nahrať artefakt
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./site"
      - name: Nasadiť GH Pages
        id: deployment
        uses: actions/deploy-pages@v3
