name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nastavi콘 Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.21

      - name: Vygenerova콘 pozn치mky
        run: |
            go run main.go poznamky

      - name: Nastavi콘 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site
