name: Vytvoriť Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nastaviť Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Vytvoriť binárky
        run: |
          go build -o poznamkovac-linux-amd64 main.go

          GOOS=windows GOARCH=amd64 go build -o poznamkovac-windows-amd64.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o poznamkovac-mac-amd64 main.go

      - name: Vytvoriť release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Vydanie ${{ github.ref }}
          body: |
            ## Zmeny

            ${{ github.event.release.body }}

      - name: Nahrať binárky
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./poznamkovac-linux-amd64
          asset_name: poznamkovac-linux-amd64
          asset_content_type: application/octet-stream

      - name: Nahrať binárky
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./poznamkovac-windows-amd64.exe
          asset_name: poznamkovac-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Nahrať binárky
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./poznamkovac-mac-amd64
          asset_name: poznamkovac-mac-amd64
          asset_content_type: application/octet-stream
